# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
# https://docs.rubocop.org/rubocop/cops_metrics.html
# https://github.com/rubocop-hq/rubocop/blob/v1.59.0/config/default.yml
# https://github.com/rubocop-hq/rubocop/blob/v1.59.0/.rubocop.yml
#
# Usage
# bundle exec rubocop --parallel --format html --out rubocop.html
# bundle exec rubocop --auto-correct-all --only Style/FrozenStringLiteralComment,Layout/EmptyLineAfterMagicComment
# bundle exec rubocop --auto-correct-all --only Style/StringLiterals,Layout/EmptyLineAfterGuardClause,Layout/EmptyLines
# bundle exec rubocop --auto-correct-all --only Layout/ExtraSpacing,Layout/SpaceAroundOperators,Layout/SpaceInsideArrayLiteralBrackets
# bundle exec rubocop --auto-correct-all --only Style/ExpandPathArguments
# bundle exec rubocop --auto-correct-all --only Style/GlobalStdStream
# bundle exec rubocop --auto-correct-all --only Style/RedundantFetchBlock

AllCops:
  SuggestExtensions: false
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  Include:
    - "**/Gemfile"
    - "**/Rakefile"
    - "**/Appraisals"
    - "**/*.rb"
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "tmp/**/*"
    - ".git/**/*"
    - "bin/*"
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "config/routes.rb"

Layout/LineLength:
  Description: 'Checks that line length does not exceed the configured limit.'
  Max: 120
  Exclude:
    - "Gemfile"

Metrics/CollectionLiteralLength:
  Description: 'Checks for `Array` or `Hash` literals with many entries.'
  Exclude:
    - "db/default/*.rb"

Layout/MultilineMethodCallIndentation:
  Description: >-
                 Checks indentation of method calls with the dot operator
                 that span more than one line.
  Enabled: false

Metrics/BlockLength:
  Description: 'Avoid long blocks with many lines.'
  Enabled: false

Metrics/MethodLength:
  Description: 'Avoid methods longer than 10 lines of code.'
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/BlockComments:
  Description: 'Do not use block comments.'
  Enabled: false

Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  Enabled: false

Style/TrailingCommaInArguments:
  Description: 'Checks for trailing comma in argument lists.'
  Enabled: false

Style/TrailingCommaInBlockArgs:
  Description: 'Checks for useless trailing commas in block arguments.'
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Description: 'Checks for trailing comma in array literals.'
  EnforcedStyleForMultiline: consistent_comma
  AutoCorrect: true

Style/TrailingCommaInHashLiteral:
  Description: 'Checks for trailing comma in hash literals.'
  EnforcedStyleForMultiline: consistent_comma
  AutoCorrect: true

Lint/EmptyBlock:
  Description: 'Checks for blocks without a body.'
  Enabled: false

Lint/RescueException:
  Description: 'Avoid rescuing the Exception class.'
  Enabled: false

Style/RescueModifier:
  Description: 'Avoid using rescue in its modifier form.'
  Enabled: false

Style/RescueStandardError:
  Description: 'Avoid rescuing without specifying an error class.'
  Enabled: false

Style/ParallelAssignment:
  Description: >-
    Check for simple usages of parallel assignment.
    It will only warn when the number of variables
    matches on both sides of the assignment.
  Enabled: false

Lint/MissingSuper:
  Description: 'This cop checks for the presence of constructors and lifecycle callbacks without calls to `super`.'
  Enabled: false

Style/MultilineTernaryOperator:
  Description: >-
                 Avoid multi-line ?: (the ternary operator);
                 use if/unless instead.
  Enabled: false
