# frozen_string_literal: true

Rails.application.reloader.to_prepare do
  ExceptionNotification.configure do |config|
    # Ignore additional exception types.
    # ActiveRecord::RecordNotFound, Mongoid::Errors::DocumentNotFound, AbstractController::ActionNotFound
    # and ActionController::RoutingError are already added.
    config.ignored_exceptions += %w[ActiveStorage::FileNotFoundError]

    # Adds a condition to decide when an exception must be ignored or not.
    # The ignore_if method can be invoked multiple times to add extra conditions.
    config.ignore_if do |_exception, _options|
      !Rails.env.production?
    end

    # Ignore exceptions generated by crawlers
    # config.ignore_crawlers %w{Googlebot bingbot}

    # Notifiers =================================================================

    # Email notifier sends notifications by email.
    # config.add_notifier :slack, {
    #   webhook_url: ENV['EXCEPTION_NOTIFICATION_SLACK_WEBHOOK_URL'],
    #   channel: "##{ENV['EXCEPTION_NOTIFICATION_SLACK_CHANNEL']}",
    #   additional_parameters: {
    #     mrkdwn: true
    #   }
    # }

    extra_config = {
      additional_parameters: {
        mrkdwn: true,
      },
    }

    config.add_notifier :slack, Slack::Notification::ExceptionListener.configuration(extra_config:)
  end
end

module ExceptionNotifier
  module SlackNotifierDecorator
    extend ActiveSupport::Concern

    private

    included do
      def call(exception, options = {})
        @hostname = options[:hostname] || ENV.fetch('EXCEPTION_HOSTNAME', Socket.gethostname)
        clean_message = exception.message.tr('`', "'")
        attchs = attchs(exception, clean_message, options)

        return unless valid?

        args = [exception, options, clean_message, @message_opts.merge(attachments: attchs)]
        send_notice(*args) do |_msg, message_opts|
          message_opts[:channel] = options[:channel] if options.key?(:channel)

          @notifier.ping '', message_opts
        end
      end

      def fields(clean_message, backtrace, data)
        fields = [
          { title: 'Exception', value: clean_message },
          { title: 'Hostname', value: @hostname },
        ]

        if backtrace
          formatted_backtrace = "```#{backtrace.first(@backtrace_lines).join("\n")}```"
          fields << { title: 'Backtrace', value: formatted_backtrace }
        end

        unless data.empty?
          deep_reject(data, @ignore_data_if) if @ignore_data_if.is_a?(Proc)
          data_string = data.map { |k, v| "#{k}: #{v}" }.join("\n")
          fields << { title: 'Data', value: "```#{data_string}```" }
        end

        fields.concat(@additional_fields) if @additional_fields

        fields
      end
    end
  end
end

ExceptionNotifier::SlackNotifier.include(ExceptionNotifier::SlackNotifierDecorator)
